#!/usr/bin/env python3
"""Turn the shared protocol vectors into a C header for the host tests.

Run by CMake at configure time; the header lands in the build directory and is never
committed, so the C tests always follow docs/content/specifications/protocol/*.json.

Usage: gen_vectors.py <out.h>
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

PROTO = Path(__file__).resolve().parents[3] / "docs/content/specifications/protocol"
EIP = json.loads((PROTO / "eip712-vectors.json").read_text())
CBOR = json.loads((PROTO / "cbor-vectors.json").read_text())
FRAME = json.loads((PROTO / "frame-vectors.json").read_text())
SESSION = json.loads((PROTO / "session-vectors.json").read_text())


def arr(b: bytes) -> str:
    return "{" + ",".join(f"0x{x:02x}" for x in b) + "}"


def hx(s: str) -> bytes:
    return bytes.fromhex(s[2:] if s.startswith("0x") else s)


def u256(v: str) -> str:
    return arr(int(v).to_bytes(32, "big"))


STRUCT = {
    "PaymentAuthorization": ("pa", [("chain_id", "u256", "chainId"), ("contract", "addr", "contract"), ("merchant", "addr", "merchant"),
                                    ("payout", "addr", "payout"), ("token", "addr", "token"), ("amount", "u256", "amount"),
                                    ("order_id", "b32", "orderId"), ("nonce", "u256", "nonce"), ("expiry", "u64", "expiry")]),
    "LimitChange": ("lc", [("chain_id", "u256", "chainId"), ("contract", "addr", "contract"), ("per_payment_limit", "u256", "perPaymentLimit"),
                           ("daily_limit", "u256", "dailyLimit"), ("nonce", "u256", "nonce"), ("expiry", "u64", "expiry")]),
    "MerchantAttestation": ("ma", [("merchant", "addr", "merchant"), ("payout", "addr", "payout"), ("name", "str", "name"),
                                   ("valid_from", "u64", "validFrom"), ("valid_until", "u64", "validUntil")]),
    "MerchantOrder": ("mo", [("order_id", "b32", "orderId"), ("token", "addr", "token"), ("amount", "u256", "amount"),
                             ("payout", "addr", "payout"), ("expiry", "u64", "expiry")]),
    "TimeAnchor": ("ta", [("device", "addr", "device"), ("timestamp", "u64", "timestamp")]),
    "DeviceReset": ("dr", [("device", "addr", "device"), ("nonce", "u256", "nonce")]),
    "WalletCheck": ("wc", [("device", "addr", "device"), ("challenge", "b32", "challenge")]),
    "KioskKey": ("kk", [("merchant", "addr", "merchant"), ("kiosk_ephemeral", "b32", "kioskEphemeral"), ("kiosk_nonce", "b32", "kioskNonce")]),
}


def field(kind: str, value: str) -> str:
    if kind == "u256":
        return u256(value)
    if kind in ("addr", "b32"):
        return arr(hx(value))
    if kind == "u64":
        return f"{int(value)}ULL"
    raise ValueError(kind)


def led_event(bodies: list[bytes]) -> int:
    """The LED event (nu54_event_t) a step's replies mean: 2 refused or error, 1 signed, 0 none."""
    ev = 0
    for b in bodies:
        if b"\x67refused" in b or b"\x65error" in b or b"\x68accepted\xf4" in b:
            ev = 2
        elif b"\x68approved" in b:
            ev = 1
    return ev


def main() -> int:
    out = ["/* Generated by test/gen_vectors.py from the shared protocol vectors. Do not edit. */",
           "#include <stddef.h>", "#include <stdint.h>", '#include "nu54_eip712.h"', "",
           f"static const uint8_t VEC_CHAIN_ID[32] = {u256(str(EIP['domain']['chainId']))};",
           f"static const uint8_t VEC_CONTRACT[20] = {arr(hx(EIP['domain']['verifyingContract']))};", ""]
    entries = []
    for n, v in enumerate(EIP["vectors"]):
        tag, fields = STRUCT[v["primaryType"]]
        m = v["message"]
        inits = []
        for cname, kind, jname in fields:
            if kind == "str":
                name = m[jname].encode()
                out.append(f"static const uint8_t VEC_NAME_{n}[] = {arr(name)};")
                inits += [f".name = VEC_NAME_{n}", f".name_len = {len(name)}"]
            else:
                inits.append(f".{cname} = {field(kind, m[jname])}")
        out.append(f"static const nu54_{dict(pa='payment_authorization', lc='limit_change', ma='merchant_attestation', mo='merchant_order', ta='time_anchor', dr='device_reset', kk='kiosk_key', wc='wallet_check')[tag]}_t VEC_MSG_{n} = {{{', '.join(inits)}}};")
        entries.append(f'{{"{v["id"]}", "{v["primaryType"]}", "{v["signerRole"]}", &VEC_MSG_{n}, {arr(hx(v["digest"]))}, {arr(hx(v["signature"]))}, {arr(hx(v["signer"]))}}}')
    out += ["", "typedef struct { const char *id; const char *type; const char *role; const void *msg; uint8_t digest[32]; uint8_t signature[65]; uint8_t signer[20]; } eip712_vector_t;",
            "static const eip712_vector_t EIP712_VECTORS[] = {", ",\n".join(entries), "};",
            f"#define EIP712_VECTOR_COUNT {len(entries)}", ""]

    bodies = {v["id"]: hx(v["cborHex"]) for v in CBOR["vectors"]}
    frames = []
    for n, v in enumerate(FRAME["valid"] + FRAME["invalid"]):
        frs = [hx(h) for h in v["fragmentsHex"]]
        for k, f in enumerate(frs):
            out.append(f"static const uint8_t FRAG_{n}_{k}[] = {arr(f)};")
        out.append(f"static const uint8_t *const FRAGS_{n}[] = {{{', '.join(f'FRAG_{n}_{k}' for k in range(len(frs)))}}};")
        out.append(f"static const size_t FRAG_LENS_{n}[] = {{{', '.join(str(len(f)) for f in frs)}}};")
        # SHA-256 prefix of the body the fragments carry, so the test can do the caller's digest
        # check without a SHA-256 of its own (on the device the platform crypto does it).
        data = b"".join(f[2:] for f in frs)
        out.append(f"static const uint8_t SHA8_{n}[8] = {arr(hashlib.sha256(data[10:]).digest()[:8])};")
        valid = "message" in v
        if valid:
            body = bodies[v["message"]]
            out.append(f"static const uint8_t BODY_{n}[] = {arr(body)};")
            frames.append(f'{{"{v["id"]}", 1, FRAGS_{n}, FRAG_LENS_{n}, {len(frs)}, BODY_{n}, {len(body)}, SHA8_{n}}}')
        else:
            frames.append(f'{{"{v["id"]}", 0, FRAGS_{n}, FRAG_LENS_{n}, {len(frs)}, NULL, 0, SHA8_{n}}}')
    out += ["typedef struct { const char *id; int valid; const uint8_t *const *frags; const size_t *lens; size_t count; const uint8_t *body; size_t body_len; const uint8_t *sha8; } frame_vector_t;",
            "static const frame_vector_t FRAME_VECTORS[] = {", ",\n".join(frames), "};",
            f"#define FRAME_VECTOR_COUNT {len(frames)}", ""]
    cb = []
    for n, v in enumerate(CBOR["vectors"]):
        out.append(f"static const uint8_t CBOR_{n}[] = {arr(hx(v['cborHex']))};")
        cb.append(f'{{"{v["id"]}", "{v["message"]["type"]}", CBOR_{n}, {len(hx(v["cborHex"]))}}}')
    out += ["typedef struct { const char *id; const char *type; const uint8_t *cbor; size_t len; } cbor_vector_t;",
            "static const cbor_vector_t CBOR_VECTORS[] = {", ",\n".join(cb), "};", f"#define CBOR_VECTOR_COUNT {len(cb)}", ""]
    dev = SESSION["device"]
    out += [f"static const uint8_t SV_KEY[32] = {arr(hx(dev['privateKey']))};",
            f"static const uint8_t SV_ADDRESS[20] = {arr(hx(dev['address']))};",
            f"static const uint8_t SV_OPERATOR[20] = {arr(hx(dev['operator']))};",
            f"static const uint8_t SV_CONTRACT[20] = {arr(hx(dev['contract']))};",
            f"static const uint8_t SV_CHAIN_ID[32] = {u256(str(dev['chainId']))};",
            f"static const uint8_t SV_NONCE_START[32] = {u256(dev['nonceStart'])};",
            f"#define SV_ANCHOR_SKEW {dev['anchorClockSkew']}", f"#define SV_AUTH_EXPIRY {dev['authorizationExpiry']}",
            f'#define SV_FIRMWARE "{dev["firmware"]}"']
    steps_all, scen = [], []
    for si, sc in enumerate(SESSION["scenarios"]):
        rows = []
        for ti, st in enumerate(sc["steps"]):
            tag = f"SV_{si}_{ti}"
            if st.get("powerCycle"):
                rows.append(f"{{{st['at']}ULL, 1, NULL, 0, {{NULL, NULL}}, {{0, 0}}, 0, NULL, 0, 0}}")
                continue
            send = hx(st["send"])
            out.append(f"static const uint8_t {tag}_SEND[] = {arr(send)};")
            ex = [hx(e) for e in st["expect"]]
            for ei, e in enumerate(ex):
                out.append(f"static const uint8_t {tag}_E{ei}[] = {arr(e)};")
            ph = hx(st["phone"][0]) if st["phone"] else None
            if ph is not None:
                out.append(f"static const uint8_t {tag}_P[] = {arr(ph)};")
            eptr = ", ".join([f"{tag}_E{i}" for i in range(len(ex))] + ["NULL"] * (2 - len(ex)))
            elen = ", ".join([str(len(e)) for e in ex] + ["0"] * (2 - len(ex)))
            # Sealed steps carry the CBOR inside them under `plain`; the event is read from those.
            plain = [hx(e) for e in st["plain"]["expect"]] if "plain" in st else list(ex)
            # wallet.check answers the phone app after the button; its refusal is a REFUSED event too.
            plain += [hx(p) for p in st["phone"] if b"wallet.check.result" in hx(p)]
            rows.append(f"{{{st['at']}ULL, 0, {tag}_SEND, {len(send)}, {{{eptr}}}, {{{elen}}}, {len(ex)}, "
                        f"{tag + '_P' if ph is not None else 'NULL'}, {len(ph) if ph is not None else 0}, {led_event(plain)}}}")
        out.append(f"static const session_step_t SV_STEPS_{si}[] = {{{', '.join(rows)}}};")
        unprov = 1 if sc.get("initialState") == "UNPROVISIONED" else 0
        pin = sc.get("pin", "2580")
        pin_c = "NULL" if pin is None else json.dumps(pin)
        secure = 1 if sc.get("requireSecureSession") else 0
        phone = 0 if sc.get("phoneConnected") is False else 1
        need_phone = 1 if sc.get("requirePhone") else 0
        bonded = 0 if sc.get("linkBonded") is False else 1
        dev_anchor = 1 if sc.get("devUnpairedAnchor") else 0
        scen.append(f'{{"{sc["id"]}", {1 if sc["button"] == "approve" else 0}, SV_STEPS_{si}, {len(rows)}, {unprov}, {pin_c}, {secure}, '
                    f'{need_phone}, {phone}, {bonded}, {dev_anchor}}}')
    out.insert(0, "typedef struct { unsigned long long at; int power_cycle; const unsigned char *send; unsigned long send_len; const unsigned char *expect[2]; unsigned long expect_len[2]; int expect_count; const unsigned char *phone; unsigned long phone_len; int event; } session_step_t;")
    out += ["/* unprovisioned: the scenario starts without key or setup values; pin: what the renter enters whenever asked (NULL: timeout);",
            "   require_secure: a release device that refuses plaintext payment sessions. Secure steps carry the AES-GCM bodies.",
            "   require_phone, phone_present, link_bonded: payment-protocol.md 3; dev_unpaired_anchor: the week-7 fixed setup. */",
            "typedef struct { const char *id; int approve; const session_step_t *steps; unsigned long count; int unprovisioned; const char *pin; int require_secure;",
            "                 int require_phone; int phone_present; int link_bonded; int dev_unpaired_anchor; } session_scenario_t;",
            "static const session_scenario_t SESSION_SCENARIOS[] = {", ",\n".join(scen), "};",
            f"#define SESSION_SCENARIO_COUNT {len(scen)}", ""]
    Path(sys.argv[1]).write_text("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
