// Generated by packages/contracts-abi/tools/generate.py from IPaymentSettlementExtensions. Do not edit.
export const paymentSettlementExtensionsAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "device",
        "type": "address"
      }
    ],
    "name": "accountOf",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "balance",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "closedAt",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "withdrawAddress",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "pendingWithdrawal",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "withdrawAfter",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "perPaymentLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dailyLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "windowStart",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "windowSpent",
            "type": "uint256"
          }
        ],
        "internalType": "struct IPaymentSettlementExtensions.AccountView",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "device",
        "type": "address"
      }
    ],
    "name": "cancelWithdrawal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "merchant",
        "type": "address"
      }
    ],
    "name": "cashOutFor",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "device",
        "type": "address"
      }
    ],
    "name": "closeAccount",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "device",
        "type": "address"
      }
    ],
    "name": "executeWithdrawal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "recoverSurplus",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "device",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "requestWithdrawal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "chainId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "contractAddress",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "perPaymentLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dailyLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "nonce",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "expiry",
            "type": "uint64"
          }
        ],
        "internalType": "struct PaymentTypes.LimitChange",
        "name": "change",
        "type": "tuple"
      },
      {
        "internalType": "bytes",
        "name": "sig",
        "type": "bytes"
      }
    ],
    "name": "setLimits",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "surplus",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalOwed",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "withdrawalDelay",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "device",
        "type": "address"
      }
    ],
    "name": "AccountClosed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "device",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "perPayment",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "daily",
        "type": "uint256"
      }
    ],
    "name": "LimitsChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "SurplusRecovered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "device",
        "type": "address"
      }
    ],
    "name": "WithdrawalCancelled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "device",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "WithdrawalExecuted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "device",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "WithdrawalRequested",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "NoPendingWithdrawal",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "WithdrawAddressMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "WithdrawalMatured",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "WithdrawalNotReady",
    "type": "error"
  }
] as const;
