// Code generated by packages/protocol/schema-gen/generate.py from payment-protocol.schema.json. DO NOT EDIT.

export const PROTOCOL_VERSION = 1 as const;

/** EIP-712 domain constants; chainId and verifyingContract come from the deployment. */
export const EIP712_DOMAIN = { name: "NU54 Payment Settlement", version: "1" } as const;

export interface PaymentAuthorization {
  chainId: bigint;
  contract: `0x${string}`;
  merchant: `0x${string}`;
  payout: `0x${string}`;
  token: `0x${string}`;
  amount: bigint;
  orderId: `0x${string}`;
  nonce: bigint;
  expiry: bigint;
}

export interface LimitChange {
  chainId: bigint;
  contract: `0x${string}`;
  perPaymentLimit: bigint;
  dailyLimit: bigint;
  nonce: bigint;
  expiry: bigint;
}

export interface WalletCheck {
  device: `0x${string}`;
  challenge: `0x${string}`;
}

export interface MerchantAttestation {
  merchant: `0x${string}`;
  payout: `0x${string}`;
  name: string;
  validFrom: bigint;
  validUntil: bigint;
}

export interface MerchantOrder {
  orderId: `0x${string}`;
  token: `0x${string}`;
  amount: bigint;
  payout: `0x${string}`;
  expiry: bigint;
}

export interface TimeAnchor {
  device: `0x${string}`;
  timestamp: bigint;
}

export interface DeviceReset {
  device: `0x${string}`;
  nonce: bigint;
}

export interface KioskKey {
  merchant: `0x${string}`;
  kioskEphemeral: `0x${string}`;
  kioskNonce: `0x${string}`;
}

export const EIP712_TYPES = {
  PaymentAuthorization: [{ name: "chainId", type: "uint256" }, { name: "contract", type: "address" }, { name: "merchant", type: "address" }, { name: "payout", type: "address" }, { name: "token", type: "address" }, { name: "amount", type: "uint256" }, { name: "orderId", type: "bytes32" }, { name: "nonce", type: "uint256" }, { name: "expiry", type: "uint64" }],
  LimitChange: [{ name: "chainId", type: "uint256" }, { name: "contract", type: "address" }, { name: "perPaymentLimit", type: "uint256" }, { name: "dailyLimit", type: "uint256" }, { name: "nonce", type: "uint256" }, { name: "expiry", type: "uint64" }],
  WalletCheck: [{ name: "device", type: "address" }, { name: "challenge", type: "bytes32" }],
  MerchantAttestation: [{ name: "merchant", type: "address" }, { name: "payout", type: "address" }, { name: "name", type: "string" }, { name: "validFrom", type: "uint64" }, { name: "validUntil", type: "uint64" }],
  MerchantOrder: [{ name: "orderId", type: "bytes32" }, { name: "token", type: "address" }, { name: "amount", type: "uint256" }, { name: "payout", type: "address" }, { name: "expiry", type: "uint64" }],
  TimeAnchor: [{ name: "device", type: "address" }, { name: "timestamp", type: "uint64" }],
  DeviceReset: [{ name: "device", type: "address" }, { name: "nonce", type: "uint256" }],
  KioskKey: [{ name: "merchant", type: "address" }, { name: "kioskEphemeral", type: "bytes32" }, { name: "kioskNonce", type: "bytes32" }],
} as const;

export const ENCODE_TYPE: Record<keyof typeof EIP712_TYPES, string> = {
  PaymentAuthorization: "PaymentAuthorization(uint256 chainId,address contract,address merchant,address payout,address token,uint256 amount,bytes32 orderId,uint256 nonce,uint64 expiry)",
  LimitChange: "LimitChange(uint256 chainId,address contract,uint256 perPaymentLimit,uint256 dailyLimit,uint256 nonce,uint64 expiry)",
  WalletCheck: "WalletCheck(address device,bytes32 challenge)",
  MerchantAttestation: "MerchantAttestation(address merchant,address payout,string name,uint64 validFrom,uint64 validUntil)",
  MerchantOrder: "MerchantOrder(bytes32 orderId,address token,uint256 amount,address payout,uint64 expiry)",
  TimeAnchor: "TimeAnchor(address device,uint64 timestamp)",
  DeviceReset: "DeviceReset(address device,uint256 nonce)",
  KioskKey: "KioskKey(address merchant,bytes32 kioskEphemeral,bytes32 kioskNonce)",
};

export const DEVICE_SIGNED_TYPES = ["PaymentAuthorization", "LimitChange"] as const;

export const REASONS = ["ATTESTATION_EXPIRED", "MERCHANT_REVOKED", "OVER_CAP", "NONCE_REPLAYED", "MERCHANT_FORGED", "USER_REJECTED", "TIME_ANCHOR_MISSING", "UNSUPPORTED_TYPE", "BAD_FRAME", "TIMEOUT", "CANCELLED", "PIN_LOCKED", "NOT_PERMITTED", "EXPIRED", "WRONG_DOMAIN", "ACCOUNT_INACTIVE", "INSUFFICIENT_BALANCE"] as const;
export type Reason = (typeof REASONS)[number];

export const OUTCOMES = ["approved", "refused", "failed", "Checking"] as const;
export type Outcome = (typeof OUTCOMES)[number];

export const MESSAGE_TYPES = ["session.open", "session.open.ok", "session.confirm", "payment.identify", "payment.prepare", "payment.result", "limit.change", "setup.timeAnchor", "error", "session.cancel", "payment.outcome", "limit.result", "setup.operator", "setup.ack", "device.reset", "confirm.show", "confirm.limit", "device.paymentMode", "device.paymentMode.ack", "device.info", "device.info.ack", "wallet.check", "wallet.check.result"] as const;
export type MessageType = (typeof MESSAGE_TYPES)[number];

/** CBOR field kinds per message (payment-protocol.md 4.2); nested objects carry their own fields. */
export type FieldKind = "hex20" | "hex32" | "signature" | "sessionId" | "uint" | "int" | "text" | "bool" | ObjectKind;
export interface ObjectKind { fields: Record<string, FieldKind>; required: readonly string[] }
export const MESSAGE_FIELDS: Record<MessageType, ObjectKind> = {
  "session.open": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "kioskNonce": "hex32",
      "mode": "text",
      "kioskEphemeral": "hex32",
      "attestation": {
        "fields": {
          "merchant": "hex20",
          "payout": "hex20",
          "name": "text",
          "validFrom": "uint",
          "validUntil": "uint",
          "operatorSignature": "signature"
        },
        "required": [
          "merchant",
          "payout",
          "name",
          "validFrom",
          "validUntil",
          "operatorSignature"
        ]
      },
      "kioskKeySignature": "signature"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "kioskNonce",
      "mode"
    ]
  },
  "session.open.ok": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "device": "hex20",
      "deviceNonce": "hex32",
      "anchorValid": "bool",
      "firmware": "text",
      "state": "text",
      "lastAnchor": "uint",
      "deviceEphemeral": "hex32"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "deviceNonce",
      "anchorValid",
      "firmware",
      "state"
    ]
  },
  "session.confirm": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "deviceNonce": "hex32"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "deviceNonce"
    ]
  },
  "payment.identify": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "attestation": {
        "fields": {
          "merchant": "hex20",
          "payout": "hex20",
          "name": "text",
          "validFrom": "uint",
          "validUntil": "uint",
          "operatorSignature": "signature"
        },
        "required": [
          "merchant",
          "payout",
          "name",
          "validFrom",
          "validUntil",
          "operatorSignature"
        ]
      }
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "attestation"
    ]
  },
  "payment.prepare": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "authorization": {
        "fields": {
          "chainId": "uint",
          "contract": "hex20",
          "merchant": "hex20",
          "payout": "hex20",
          "token": "hex20",
          "amount": "uint",
          "orderId": "hex32",
          "expiry": "uint"
        },
        "required": [
          "chainId",
          "contract",
          "merchant",
          "payout",
          "token",
          "amount",
          "orderId",
          "expiry"
        ]
      },
      "merchantSignature": "signature"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "authorization",
      "merchantSignature"
    ]
  },
  "payment.result": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "outcome": "text",
      "signature": "signature",
      "reason": "text",
      "nonce": "uint"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "outcome"
    ]
  },
  "limit.change": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "change": {
        "fields": {
          "chainId": "uint",
          "contract": "hex20",
          "perPaymentLimit": "uint",
          "dailyLimit": "uint",
          "expiry": "uint"
        },
        "required": [
          "chainId",
          "contract",
          "perPaymentLimit",
          "dailyLimit",
          "expiry"
        ]
      }
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "change"
    ]
  },
  "setup.timeAnchor": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "timestamp": "uint",
      "operatorSignature": "signature",
      "device": "hex20"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "device",
      "timestamp",
      "operatorSignature"
    ]
  },
  "error": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "reason": "text"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "reason"
    ]
  },
  "session.cancel": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId"
    },
    "required": [
      "v",
      "type",
      "sessionId"
    ]
  },
  "payment.outcome": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "orderId": "hex32",
      "outcome": "text",
      "reason": "text",
      "txHash": "hex32",
      "receipt": "text"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "orderId",
      "outcome"
    ]
  },
  "limit.result": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "outcome": "text",
      "signature": "signature",
      "nonce": "uint",
      "reason": "text"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "outcome"
    ]
  },
  "setup.operator": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "operator": "hex20",
      "contract": "hex20",
      "chainId": "uint",
      "passkey": "uint"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "operator",
      "contract",
      "chainId",
      "passkey"
    ]
  },
  "setup.ack": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "step": "text",
      "accepted": "bool",
      "reason": "text",
      "device": "hex20",
      "lastAnchor": "uint"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "step",
      "accepted"
    ]
  },
  "device.reset": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "device": "hex20",
      "nonce": "uint",
      "operatorSignature": "signature"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "device",
      "nonce",
      "operatorSignature"
    ]
  },
  "confirm.show": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "merchantName": "text",
      "orderId": "hex32",
      "token": "hex20",
      "payout": "hex20",
      "amount": "uint"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "merchantName",
      "orderId",
      "token",
      "payout",
      "amount"
    ]
  },
  "confirm.limit": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "perPaymentLimit": "uint",
      "dailyLimit": "uint",
      "expiry": "uint"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "perPaymentLimit",
      "dailyLimit",
      "expiry"
    ]
  },
  "device.paymentMode": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "on": "bool",
      "seconds": "uint"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "on",
      "seconds"
    ]
  },
  "device.paymentMode.ack": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "accepted": "bool",
      "on": "bool",
      "reason": "text"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "accepted",
      "on"
    ]
  },
  "device.info": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId"
    },
    "required": [
      "v",
      "type",
      "sessionId"
    ]
  },
  "device.info.ack": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "state": "text",
      "firmware": "text",
      "anchorValid": "bool",
      "device": "hex20"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "state",
      "firmware",
      "anchorValid"
    ]
  },
  "wallet.check": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "challenge": "hex32"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "challenge"
    ]
  },
  "wallet.check.result": {
    "fields": {
      "v": "int",
      "type": "text",
      "sessionId": "sessionId",
      "accepted": "bool",
      "signature": "signature",
      "reason": "text"
    },
    "required": [
      "v",
      "type",
      "sessionId",
      "accepted"
    ]
  }
};

/** GATT service of the payment protocol (payment-protocol.md 3). */
export const GATT = { service: "6e753534-7061-7900-8000-00805f9b0001", rx: "6e753534-7061-7900-8000-00805f9b0002", tx: "6e753534-7061-7900-8000-00805f9b0003" } as const;
