// Code generated by packages/protocol/schema-gen/generate.py from payment-protocol.schema.json. DO NOT EDIT.

export const PROTOCOL_VERSION = 1 as const;

export interface PaymentAuthorization {
  chainId: bigint;
  contract: `0x${string}`;
  merchant: `0x${string}`;
  payout: `0x${string}`;
  token: `0x${string}`;
  amount: bigint;
  orderId: `0x${string}`;
  nonce: bigint;
  expiry: bigint;
}

export interface LimitChange {
  chainId: bigint;
  contract: `0x${string}`;
  perPaymentLimit: bigint;
  dailyLimit: bigint;
  nonce: bigint;
  expiry: bigint;
}

export interface MerchantAttestation {
  merchant: `0x${string}`;
  payout: `0x${string}`;
  name: string;
  validFrom: bigint;
  validUntil: bigint;
}

export interface MerchantOrder {
  orderId: `0x${string}`;
  token: `0x${string}`;
  amount: bigint;
  payout: `0x${string}`;
  expiry: bigint;
}

export interface TimeAnchor {
  device: `0x${string}`;
  timestamp: bigint;
}

export interface DeviceReset {
  device: `0x${string}`;
  nonce: bigint;
}

export const EIP712_TYPES = {
  PaymentAuthorization: [{ name: "chainId", type: "uint256" }, { name: "contract", type: "address" }, { name: "merchant", type: "address" }, { name: "payout", type: "address" }, { name: "token", type: "address" }, { name: "amount", type: "uint256" }, { name: "orderId", type: "bytes32" }, { name: "nonce", type: "uint256" }, { name: "expiry", type: "uint64" }],
  LimitChange: [{ name: "chainId", type: "uint256" }, { name: "contract", type: "address" }, { name: "perPaymentLimit", type: "uint256" }, { name: "dailyLimit", type: "uint256" }, { name: "nonce", type: "uint256" }, { name: "expiry", type: "uint64" }],
  MerchantAttestation: [{ name: "merchant", type: "address" }, { name: "payout", type: "address" }, { name: "name", type: "string" }, { name: "validFrom", type: "uint64" }, { name: "validUntil", type: "uint64" }],
  MerchantOrder: [{ name: "orderId", type: "bytes32" }, { name: "token", type: "address" }, { name: "amount", type: "uint256" }, { name: "payout", type: "address" }, { name: "expiry", type: "uint64" }],
  TimeAnchor: [{ name: "device", type: "address" }, { name: "timestamp", type: "uint64" }],
  DeviceReset: [{ name: "device", type: "address" }, { name: "nonce", type: "uint256" }],
} as const;

export const ENCODE_TYPE: Record<keyof typeof EIP712_TYPES, string> = {
  PaymentAuthorization: "PaymentAuthorization(uint256 chainId,address contract,address merchant,address payout,address token,uint256 amount,bytes32 orderId,uint256 nonce,uint64 expiry)",
  LimitChange: "LimitChange(uint256 chainId,address contract,uint256 perPaymentLimit,uint256 dailyLimit,uint256 nonce,uint64 expiry)",
  MerchantAttestation: "MerchantAttestation(address merchant,address payout,string name,uint64 validFrom,uint64 validUntil)",
  MerchantOrder: "MerchantOrder(bytes32 orderId,address token,uint256 amount,address payout,uint64 expiry)",
  TimeAnchor: "TimeAnchor(address device,uint64 timestamp)",
  DeviceReset: "DeviceReset(address device,uint256 nonce)",
};

export const DEVICE_SIGNED_TYPES = ["PaymentAuthorization", "LimitChange"] as const;

export const REASONS = ["ATTESTATION_EXPIRED", "MERCHANT_REVOKED", "OVER_CAP", "NONCE_REPLAYED", "MERCHANT_FORGED", "USER_REJECTED", "TIME_ANCHOR_MISSING", "UNSUPPORTED_TYPE", "BAD_FRAME", "TIMEOUT", "CANCELLED", "PIN_LOCKED", "NOT_PERMITTED", "EXPIRED", "WRONG_DOMAIN", "ACCOUNT_INACTIVE", "INSUFFICIENT_BALANCE"] as const;
export type Reason = (typeof REASONS)[number];

export const OUTCOMES = ["approved", "refused", "failed", "Checking"] as const;
export type Outcome = (typeof OUTCOMES)[number];

export const MESSAGE_TYPES = ["session.open", "session.open.ok", "session.confirm", "payment.identify", "payment.prepare", "payment.result", "limit.change", "setup.timeAnchor", "error", "session.cancel", "payment.outcome", "limit.result", "setup.operator", "setup.ack", "device.reset", "confirm.show"] as const;
export type MessageType = (typeof MESSAGE_TYPES)[number];
