#!/usr/bin/env python3
"""Generate contract ABI artifacts from the settlement contracts.

Source: products/p06-stablenet-contracts (Foundry). Outputs:
  abi/<Name>.json          ABI JSON, keys sorted for stable diffs
  abi/manifest.json        sha256 of each ABI; the frozen interfaces are listed as such
  ts/src/<name>.ts         `export const <name>Abi = [...] as const` for viem-style typing
  go/<pkg>/<pkg>.go        Go bindings from go-ethereum abigen

Usage:
  python3 tools/generate.py           regenerate everything
  python3 tools/generate.py --check   fail if any committed file differs from a fresh build
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
REPO = HERE.parents[1]
CONTRACTS = REPO / "products/p06-stablenet-contracts"
ABIGEN = "github.com/ethereum/go-ethereum/cmd/abigen@v1.16.4"

# (contract name in Foundry, Go package, TS identifier, frozen at the W6 contract gate)
TARGETS = [
    ("IPaymentSettlement", "settlement", "paymentSettlement", True),
    ("IMerchantRegistry", "registry", "merchantRegistry", True),
    ("TestUSDC", "testusdc", "testUsdc", False),
]


def forge_abi(name: str) -> list:
    out = subprocess.run(["forge", "inspect", name, "abi", "--json"], cwd=CONTRACTS, check=True,
                         capture_output=True, text=True).stdout
    return json.loads(out)


def abigen(abi_path: Path, pkg: str, out_path: Path) -> None:
    subprocess.run(["go", "run", ABIGEN, "--abi", str(abi_path), "--pkg", pkg, "--type", pkg.capitalize(),
                    "--out", str(out_path)], cwd=HERE / "go", check=True, capture_output=True, text=True)


def render(workdir: Path) -> dict[str, str]:
    """Build every output into memory: {relative path: content}."""
    files: dict[str, str] = {}
    manifest = {"source": "products/p06-stablenet-contracts", "abis": {}}
    ts_index = []
    for name, pkg, ts_id, frozen in TARGETS:
        abi = forge_abi(name)
        abi_json = json.dumps(abi, indent=2, sort_keys=True) + "\n"
        files[f"abi/{name}.json"] = abi_json
        manifest["abis"][name] = {"sha256": hashlib.sha256(abi_json.encode()).hexdigest(), "frozenAtW6": frozen}
        files[f"ts/src/{ts_id}.ts"] = (
            f"// Generated by packages/contracts-abi/tools/generate.py from {name}. Do not edit.\n"
            f"export const {ts_id}Abi = {json.dumps(abi, indent=2, sort_keys=True)} as const;\n"
        )
        ts_index.append(f'export {{ {ts_id}Abi }} from "./{ts_id}.ts";')
        tmp_abi = workdir / f"{name}.json"
        tmp_abi.write_text(abi_json)
        tmp_go = workdir / f"{pkg}.go"
        abigen(tmp_abi, pkg, tmp_go)
        files[f"go/{pkg}/{pkg}.go"] = tmp_go.read_text()
    files["abi/manifest.json"] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    files["ts/src/index.ts"] = "// Generated by packages/contracts-abi/tools/generate.py. Do not edit.\n" + "\n".join(ts_index) + "\n"
    return files


def main(argv: list[str]) -> int:
    check = "--check" in argv
    subprocess.run(["forge", "build", "--quiet"], cwd=CONTRACTS, check=True)
    with tempfile.TemporaryDirectory() as tmp:
        files = render(Path(tmp))
    stale = []
    for rel, content in files.items():
        path = HERE / rel
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if check and stale:
        print("stale generated files (run python3 tools/generate.py):", *stale, sep="\n  ")
        return 1
    print("checked" if check else "generated", len(files), "files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
