#!/usr/bin/env python3
"""Write the development fixed setup (week 7) from the deployment record.

The values setup.operator would record (operator, settlement contract, chain id) are taken
from products/p06-stablenet-contracts/deployments/<chain>.json, never typed by hand. The week-8
setup session replaces this header (payment-protocol.md 5).

Usage: gen_dev_setup.py <deployment.json> <out.h>
"""

import json
import sys
from pathlib import Path


def arr(b: bytes) -> str:
    return "{" + ", ".join(f"0x{x:02x}" for x in b) + "}"


dep = json.loads(Path(sys.argv[1]).read_text())
operator = bytes.fromhex(dep["roles"]["operator"][2:])
contract = bytes.fromhex(dep["contracts"]["PaymentSettlement"]["address"][2:])
chain = int(dep["chainId"]).to_bytes(32, "big")
Path(sys.argv[2]).write_text(
    "/* Generated by app/gen_dev_setup.py from the deployment record. Do not edit. */\n"
    "#ifndef DEV_SETUP_H\n#define DEV_SETUP_H\n#include <stdint.h>\n"
    f"static const uint8_t DEV_OPERATOR[20] = {arr(operator)};\n"
    f"static const uint8_t DEV_CONTRACT[20] = {arr(contract)};\n"
    f"static const uint8_t DEV_CHAIN_ID[32] = {arr(chain)};\n"
    f"#define DEV_CHAIN_ID_NUMBER {int(dep['chainId'])}\n"
    "#endif\n"
)
