/* Code generated by packages/protocol/schema-gen/generate.py from payment-protocol.schema.json. DO NOT EDIT. */
#ifndef NU54_PROTOCOL_H
#define NU54_PROTOCOL_H

#define NU54_PROTOCOL_VERSION 1

#define NU54_ENCODE_TYPE_PAYMENT_AUTHORIZATION "PaymentAuthorization(uint256 chainId,address contract,address merchant,address payout,address token,uint256 amount,bytes32 orderId,uint256 nonce,uint64 expiry)"
#define NU54_FIELDS_PAYMENT_AUTHORIZATION 9
#define NU54_ENCODE_TYPE_LIMIT_CHANGE "LimitChange(uint256 chainId,address contract,uint256 perPaymentLimit,uint256 dailyLimit,uint256 nonce,uint64 expiry)"
#define NU54_FIELDS_LIMIT_CHANGE 6
#define NU54_ENCODE_TYPE_MERCHANT_ATTESTATION "MerchantAttestation(address merchant,address payout,string name,uint64 validFrom,uint64 validUntil)"
#define NU54_FIELDS_MERCHANT_ATTESTATION 5
#define NU54_ENCODE_TYPE_MERCHANT_ORDER "MerchantOrder(bytes32 orderId,address token,uint256 amount,address payout,uint64 expiry)"
#define NU54_FIELDS_MERCHANT_ORDER 5
#define NU54_ENCODE_TYPE_TIME_ANCHOR "TimeAnchor(address device,uint64 timestamp)"
#define NU54_FIELDS_TIME_ANCHOR 2
#define NU54_ENCODE_TYPE_DEVICE_RESET "DeviceReset(address device,uint256 nonce)"
#define NU54_FIELDS_DEVICE_RESET 2

typedef enum {
    NU54_REASON_ATTESTATION_EXPIRED = 0,
    NU54_REASON_MERCHANT_REVOKED = 1,
    NU54_REASON_OVER_CAP = 2,
    NU54_REASON_NONCE_REPLAYED = 3,
    NU54_REASON_MERCHANT_FORGED = 4,
    NU54_REASON_USER_REJECTED = 5,
    NU54_REASON_TIME_ANCHOR_MISSING = 6,
    NU54_REASON_UNSUPPORTED_TYPE = 7,
    NU54_REASON_BAD_FRAME = 8,
    NU54_REASON_TIMEOUT = 9,
    NU54_REASON_CANCELLED = 10,
    NU54_REASON_PIN_LOCKED = 11,
    NU54_REASON_NOT_PERMITTED = 12,
    NU54_REASON_EXPIRED = 13,
    NU54_REASON_WRONG_DOMAIN = 14,
    NU54_REASON_ACCOUNT_INACTIVE = 15,
    NU54_REASON_INSUFFICIENT_BALANCE = 16,
    NU54_REASON_COUNT
} nu54_reason_t;

static const char *const nu54_reason_str[] = {
    "ATTESTATION_EXPIRED",
    "MERCHANT_REVOKED",
    "OVER_CAP",
    "NONCE_REPLAYED",
    "MERCHANT_FORGED",
    "USER_REJECTED",
    "TIME_ANCHOR_MISSING",
    "UNSUPPORTED_TYPE",
    "BAD_FRAME",
    "TIMEOUT",
    "CANCELLED",
    "PIN_LOCKED",
    "NOT_PERMITTED",
    "EXPIRED",
    "WRONG_DOMAIN",
    "ACCOUNT_INACTIVE",
    "INSUFFICIENT_BALANCE",
};

#endif /* NU54_PROTOCOL_H */
