// Code generated by packages/protocol/schema-gen/generate.py from payment-protocol.schema.json. DO NOT EDIT.

package protocol

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

// ProtocolVersion is the BLE payload version (field v).
const ProtocolVersion = 1

// PaymentAuthorization is an EIP-712 struct signed by the device.
type PaymentAuthorization struct {
	ChainId  *big.Int       `json:"chainId"`
	Contract common.Address `json:"contract"`
	Merchant common.Address `json:"merchant"`
	Payout   common.Address `json:"payout"`
	Token    common.Address `json:"token"`
	Amount   *big.Int       `json:"amount"`
	OrderId  [32]byte       `json:"orderId"`
	Nonce    *big.Int       `json:"nonce"`
	Expiry   uint64         `json:"expiry"`
}

// LimitChange is an EIP-712 struct signed by the device.
type LimitChange struct {
	ChainId         *big.Int       `json:"chainId"`
	Contract        common.Address `json:"contract"`
	PerPaymentLimit *big.Int       `json:"perPaymentLimit"`
	DailyLimit      *big.Int       `json:"dailyLimit"`
	Nonce           *big.Int       `json:"nonce"`
	Expiry          uint64         `json:"expiry"`
}

// MerchantAttestation is an EIP-712 struct signed by the operator or merchant.
type MerchantAttestation struct {
	Merchant   common.Address `json:"merchant"`
	Payout     common.Address `json:"payout"`
	Name       string         `json:"name"`
	ValidFrom  uint64         `json:"validFrom"`
	ValidUntil uint64         `json:"validUntil"`
}

// MerchantOrder is an EIP-712 struct signed by the operator or merchant.
type MerchantOrder struct {
	OrderId [32]byte       `json:"orderId"`
	Token   common.Address `json:"token"`
	Amount  *big.Int       `json:"amount"`
	Payout  common.Address `json:"payout"`
	Expiry  uint64         `json:"expiry"`
}

// TimeAnchor is an EIP-712 struct signed by the operator or merchant.
type TimeAnchor struct {
	Device    common.Address `json:"device"`
	Timestamp uint64         `json:"timestamp"`
}

// DeviceReset is an EIP-712 struct signed by the operator or merchant.
type DeviceReset struct {
	Device common.Address `json:"device"`
	Nonce  *big.Int       `json:"nonce"`
}

// EncodeType holds the EIP-712 encodeType string of every struct.
var EncodeType = map[string]string{
	"PaymentAuthorization": "PaymentAuthorization(uint256 chainId,address contract,address merchant,address payout,address token,uint256 amount,bytes32 orderId,uint256 nonce,uint64 expiry)",
	"LimitChange":          "LimitChange(uint256 chainId,address contract,uint256 perPaymentLimit,uint256 dailyLimit,uint256 nonce,uint64 expiry)",
	"MerchantAttestation":  "MerchantAttestation(address merchant,address payout,string name,uint64 validFrom,uint64 validUntil)",
	"MerchantOrder":        "MerchantOrder(bytes32 orderId,address token,uint256 amount,address payout,uint64 expiry)",
	"TimeAnchor":           "TimeAnchor(address device,uint64 timestamp)",
	"DeviceReset":          "DeviceReset(address device,uint256 nonce)",
}

// DeviceSignedTypes are the only structs the device signs ([N04]).
var DeviceSignedTypes = []string{"PaymentAuthorization", "LimitChange"}

// Reason is a refusal or session code.
type Reason string

const (
	ReasonAttestationExpired  Reason = "ATTESTATION_EXPIRED"
	ReasonMerchantRevoked     Reason = "MERCHANT_REVOKED"
	ReasonOverCap             Reason = "OVER_CAP"
	ReasonNonceReplayed       Reason = "NONCE_REPLAYED"
	ReasonMerchantForged      Reason = "MERCHANT_FORGED"
	ReasonUserRejected        Reason = "USER_REJECTED"
	ReasonTimeAnchorMissing   Reason = "TIME_ANCHOR_MISSING"
	ReasonUnsupportedType     Reason = "UNSUPPORTED_TYPE"
	ReasonBadFrame            Reason = "BAD_FRAME"
	ReasonTimeout             Reason = "TIMEOUT"
	ReasonCancelled           Reason = "CANCELLED"
	ReasonPinLocked           Reason = "PIN_LOCKED"
	ReasonNotPermitted        Reason = "NOT_PERMITTED"
	ReasonExpired             Reason = "EXPIRED"
	ReasonWrongDomain         Reason = "WRONG_DOMAIN"
	ReasonAccountInactive     Reason = "ACCOUNT_INACTIVE"
	ReasonInsufficientBalance Reason = "INSUFFICIENT_BALANCE"
)

// Outcome is a kiosk-visible payment outcome.
type Outcome string

const (
	OutcomeApproved Outcome = "approved"
	OutcomeRefused  Outcome = "refused"
	OutcomeFailed   Outcome = "failed"
	OutcomeChecking Outcome = "Checking"
)

// MessageTypes lists every BLE message type in the schema.
var MessageTypes = []string{
	"session.open",
	"session.open.ok",
	"session.confirm",
	"payment.identify",
	"payment.prepare",
	"payment.result",
	"limit.change",
	"setup.timeAnchor",
	"error",
	"session.cancel",
	"payment.outcome",
	"limit.result",
	"setup.operator",
	"setup.ack",
	"device.reset",
	"confirm.show",
}
