// Code generated by packages/protocol/schema-gen/generate.py from payment-protocol.schema.json. DO NOT EDIT.

package protocol

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

// ProtocolVersion is the BLE payload version (field v).
const ProtocolVersion = 1

// PaymentAuthorization is an EIP-712 struct signed by the device.
type PaymentAuthorization struct {
	ChainId  *big.Int       `json:"chainId"`
	Contract common.Address `json:"contract"`
	Merchant common.Address `json:"merchant"`
	Payout   common.Address `json:"payout"`
	Token    common.Address `json:"token"`
	Amount   *big.Int       `json:"amount"`
	OrderId  [32]byte       `json:"orderId"`
	Nonce    *big.Int       `json:"nonce"`
	Expiry   uint64         `json:"expiry"`
}

// LimitChange is an EIP-712 struct signed by the device.
type LimitChange struct {
	ChainId         *big.Int       `json:"chainId"`
	Contract        common.Address `json:"contract"`
	PerPaymentLimit *big.Int       `json:"perPaymentLimit"`
	DailyLimit      *big.Int       `json:"dailyLimit"`
	Nonce           *big.Int       `json:"nonce"`
	Expiry          uint64         `json:"expiry"`
}

// MerchantAttestation is an EIP-712 struct signed by the operator or merchant.
type MerchantAttestation struct {
	Merchant   common.Address `json:"merchant"`
	Payout     common.Address `json:"payout"`
	Name       string         `json:"name"`
	ValidFrom  uint64         `json:"validFrom"`
	ValidUntil uint64         `json:"validUntil"`
}

// MerchantOrder is an EIP-712 struct signed by the operator or merchant.
type MerchantOrder struct {
	OrderId [32]byte       `json:"orderId"`
	Token   common.Address `json:"token"`
	Amount  *big.Int       `json:"amount"`
	Payout  common.Address `json:"payout"`
	Expiry  uint64         `json:"expiry"`
}

// TimeAnchor is an EIP-712 struct signed by the operator or merchant.
type TimeAnchor struct {
	Device    common.Address `json:"device"`
	Timestamp uint64         `json:"timestamp"`
}

// DeviceReset is an EIP-712 struct signed by the operator or merchant.
type DeviceReset struct {
	Device common.Address `json:"device"`
	Nonce  *big.Int       `json:"nonce"`
}

// KioskKey is an EIP-712 struct signed by the operator or merchant.
type KioskKey struct {
	Merchant       common.Address `json:"merchant"`
	KioskEphemeral [32]byte       `json:"kioskEphemeral"`
	KioskNonce     [32]byte       `json:"kioskNonce"`
}

// EncodeType holds the EIP-712 encodeType string of every struct.
var EncodeType = map[string]string{
	"PaymentAuthorization": "PaymentAuthorization(uint256 chainId,address contract,address merchant,address payout,address token,uint256 amount,bytes32 orderId,uint256 nonce,uint64 expiry)",
	"LimitChange":          "LimitChange(uint256 chainId,address contract,uint256 perPaymentLimit,uint256 dailyLimit,uint256 nonce,uint64 expiry)",
	"MerchantAttestation":  "MerchantAttestation(address merchant,address payout,string name,uint64 validFrom,uint64 validUntil)",
	"MerchantOrder":        "MerchantOrder(bytes32 orderId,address token,uint256 amount,address payout,uint64 expiry)",
	"TimeAnchor":           "TimeAnchor(address device,uint64 timestamp)",
	"DeviceReset":          "DeviceReset(address device,uint256 nonce)",
	"KioskKey":             "KioskKey(address merchant,bytes32 kioskEphemeral,bytes32 kioskNonce)",
}

// DeviceSignedTypes are the only structs the device signs ([N04]).
var DeviceSignedTypes = []string{"PaymentAuthorization", "LimitChange"}

// Reason is a refusal or session code.
type Reason string

const (
	ReasonAttestationExpired  Reason = "ATTESTATION_EXPIRED"
	ReasonMerchantRevoked     Reason = "MERCHANT_REVOKED"
	ReasonOverCap             Reason = "OVER_CAP"
	ReasonNonceReplayed       Reason = "NONCE_REPLAYED"
	ReasonMerchantForged      Reason = "MERCHANT_FORGED"
	ReasonUserRejected        Reason = "USER_REJECTED"
	ReasonTimeAnchorMissing   Reason = "TIME_ANCHOR_MISSING"
	ReasonUnsupportedType     Reason = "UNSUPPORTED_TYPE"
	ReasonBadFrame            Reason = "BAD_FRAME"
	ReasonTimeout             Reason = "TIMEOUT"
	ReasonCancelled           Reason = "CANCELLED"
	ReasonPinLocked           Reason = "PIN_LOCKED"
	ReasonNotPermitted        Reason = "NOT_PERMITTED"
	ReasonExpired             Reason = "EXPIRED"
	ReasonWrongDomain         Reason = "WRONG_DOMAIN"
	ReasonAccountInactive     Reason = "ACCOUNT_INACTIVE"
	ReasonInsufficientBalance Reason = "INSUFFICIENT_BALANCE"
)

// Outcome is a kiosk-visible payment outcome.
type Outcome string

const (
	OutcomeApproved Outcome = "approved"
	OutcomeRefused  Outcome = "refused"
	OutcomeFailed   Outcome = "failed"
	OutcomeChecking Outcome = "Checking"
)

// MessageTypes lists every BLE message type in the schema.
var MessageTypes = []string{
	"session.open",
	"session.open.ok",
	"session.confirm",
	"payment.identify",
	"payment.prepare",
	"payment.result",
	"limit.change",
	"setup.timeAnchor",
	"error",
	"session.cancel",
	"payment.outcome",
	"limit.result",
	"setup.operator",
	"setup.ack",
	"device.reset",
	"confirm.show",
	"confirm.limit",
	"device.paymentMode",
	"device.paymentMode.ack",
}

// FieldKind is the CBOR kind of a message field (payment-protocol.md 4.2): a scalar kind name,
// or a nested object.
type FieldKind struct {
	Name   string
	Object *ObjectKind
}

// ObjectKind lists an object's fields and the required ones.
type ObjectKind struct {
	Fields   map[string]FieldKind
	Required []string
}

// MessageFields gives the field kinds of every message, as in the schema.
var MessageFields = map[string]*ObjectKind{
	"session.open": &ObjectKind{Fields: map[string]FieldKind{
		"v":              {Name: "int"},
		"type":           {Name: "text"},
		"sessionId":      {Name: "sessionId"},
		"kioskNonce":     {Name: "hex32"},
		"mode":           {Name: "text"},
		"kioskEphemeral": {Name: "hex32"},
		"attestation": {Object: &ObjectKind{Fields: map[string]FieldKind{
			"merchant":          {Name: "hex20"},
			"payout":            {Name: "hex20"},
			"name":              {Name: "text"},
			"validFrom":         {Name: "uint"},
			"validUntil":        {Name: "uint"},
			"operatorSignature": {Name: "signature"},
		}, Required: []string{"merchant", "payout", "name", "validFrom", "validUntil", "operatorSignature"}}},
		"kioskKeySignature": {Name: "signature"},
	}, Required: []string{"v", "type", "sessionId", "kioskNonce", "mode"}},
	"session.open.ok": &ObjectKind{Fields: map[string]FieldKind{
		"v":               {Name: "int"},
		"type":            {Name: "text"},
		"sessionId":       {Name: "sessionId"},
		"device":          {Name: "hex20"},
		"deviceNonce":     {Name: "hex32"},
		"anchorValid":     {Name: "bool"},
		"firmware":        {Name: "text"},
		"state":           {Name: "text"},
		"lastAnchor":      {Name: "uint"},
		"deviceEphemeral": {Name: "hex32"},
	}, Required: []string{"v", "type", "sessionId", "deviceNonce", "anchorValid", "firmware", "state"}},
	"session.confirm": &ObjectKind{Fields: map[string]FieldKind{
		"v":           {Name: "int"},
		"type":        {Name: "text"},
		"sessionId":   {Name: "sessionId"},
		"deviceNonce": {Name: "hex32"},
	}, Required: []string{"v", "type", "sessionId", "deviceNonce"}},
	"payment.identify": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"attestation": {Object: &ObjectKind{Fields: map[string]FieldKind{
			"merchant":          {Name: "hex20"},
			"payout":            {Name: "hex20"},
			"name":              {Name: "text"},
			"validFrom":         {Name: "uint"},
			"validUntil":        {Name: "uint"},
			"operatorSignature": {Name: "signature"},
		}, Required: []string{"merchant", "payout", "name", "validFrom", "validUntil", "operatorSignature"}}},
	}, Required: []string{"v", "type", "sessionId", "attestation"}},
	"payment.prepare": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"authorization": {Object: &ObjectKind{Fields: map[string]FieldKind{
			"chainId":  {Name: "uint"},
			"contract": {Name: "hex20"},
			"merchant": {Name: "hex20"},
			"payout":   {Name: "hex20"},
			"token":    {Name: "hex20"},
			"amount":   {Name: "uint"},
			"orderId":  {Name: "hex32"},
			"expiry":   {Name: "uint"},
		}, Required: []string{"chainId", "contract", "merchant", "payout", "token", "amount", "orderId", "expiry"}}},
		"merchantSignature": {Name: "signature"},
	}, Required: []string{"v", "type", "sessionId", "authorization", "merchantSignature"}},
	"payment.result": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"outcome":   {Name: "text"},
		"signature": {Name: "signature"},
		"reason":    {Name: "text"},
		"nonce":     {Name: "uint"},
	}, Required: []string{"v", "type", "sessionId", "outcome"}},
	"limit.change": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"change": {Object: &ObjectKind{Fields: map[string]FieldKind{
			"chainId":         {Name: "uint"},
			"contract":        {Name: "hex20"},
			"perPaymentLimit": {Name: "uint"},
			"dailyLimit":      {Name: "uint"},
			"expiry":          {Name: "uint"},
		}, Required: []string{"chainId", "contract", "perPaymentLimit", "dailyLimit", "expiry"}}},
	}, Required: []string{"v", "type", "sessionId", "change"}},
	"setup.timeAnchor": &ObjectKind{Fields: map[string]FieldKind{
		"v":                 {Name: "int"},
		"type":              {Name: "text"},
		"sessionId":         {Name: "sessionId"},
		"timestamp":         {Name: "uint"},
		"operatorSignature": {Name: "signature"},
		"device":            {Name: "hex20"},
	}, Required: []string{"v", "type", "sessionId", "device", "timestamp", "operatorSignature"}},
	"error": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"reason":    {Name: "text"},
	}, Required: []string{"v", "type", "sessionId", "reason"}},
	"session.cancel": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
	}, Required: []string{"v", "type", "sessionId"}},
	"payment.outcome": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"orderId":   {Name: "hex32"},
		"outcome":   {Name: "text"},
		"reason":    {Name: "text"},
	}, Required: []string{"v", "type", "sessionId", "orderId", "outcome"}},
	"limit.result": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"outcome":   {Name: "text"},
		"signature": {Name: "signature"},
		"nonce":     {Name: "uint"},
		"reason":    {Name: "text"},
	}, Required: []string{"v", "type", "sessionId", "outcome"}},
	"setup.operator": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"operator":  {Name: "hex20"},
		"contract":  {Name: "hex20"},
		"chainId":   {Name: "uint"},
		"passkey":   {Name: "uint"},
	}, Required: []string{"v", "type", "sessionId", "operator", "contract", "chainId", "passkey"}},
	"setup.ack": &ObjectKind{Fields: map[string]FieldKind{
		"v":          {Name: "int"},
		"type":       {Name: "text"},
		"sessionId":  {Name: "sessionId"},
		"step":       {Name: "text"},
		"accepted":   {Name: "bool"},
		"reason":     {Name: "text"},
		"device":     {Name: "hex20"},
		"lastAnchor": {Name: "uint"},
	}, Required: []string{"v", "type", "sessionId", "step", "accepted"}},
	"device.reset": &ObjectKind{Fields: map[string]FieldKind{
		"v":                 {Name: "int"},
		"type":              {Name: "text"},
		"sessionId":         {Name: "sessionId"},
		"device":            {Name: "hex20"},
		"nonce":             {Name: "uint"},
		"operatorSignature": {Name: "signature"},
	}, Required: []string{"v", "type", "sessionId", "device", "nonce", "operatorSignature"}},
	"confirm.show": &ObjectKind{Fields: map[string]FieldKind{
		"v":            {Name: "int"},
		"type":         {Name: "text"},
		"sessionId":    {Name: "sessionId"},
		"merchantName": {Name: "text"},
		"orderId":      {Name: "hex32"},
		"token":        {Name: "hex20"},
		"payout":       {Name: "hex20"},
		"amount":       {Name: "uint"},
	}, Required: []string{"v", "type", "sessionId", "merchantName", "orderId", "token", "payout", "amount"}},
	"confirm.limit": &ObjectKind{Fields: map[string]FieldKind{
		"v":               {Name: "int"},
		"type":            {Name: "text"},
		"sessionId":       {Name: "sessionId"},
		"perPaymentLimit": {Name: "uint"},
		"dailyLimit":      {Name: "uint"},
		"expiry":          {Name: "uint"},
	}, Required: []string{"v", "type", "sessionId", "perPaymentLimit", "dailyLimit", "expiry"}},
	"device.paymentMode": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"on":        {Name: "bool"},
		"seconds":   {Name: "uint"},
	}, Required: []string{"v", "type", "sessionId", "on", "seconds"}},
	"device.paymentMode.ack": &ObjectKind{Fields: map[string]FieldKind{
		"v":         {Name: "int"},
		"type":      {Name: "text"},
		"sessionId": {Name: "sessionId"},
		"accepted":  {Name: "bool"},
		"on":        {Name: "bool"},
		"reason":    {Name: "text"},
	}, Required: []string{"v", "type", "sessionId", "accepted", "on"}},
}

// GATT service of the payment protocol (payment-protocol.md 3).
const (
	GATTService = "6e753534-7061-7900-8000-00805f9b0001"
	GATTRx      = "6e753534-7061-7900-8000-00805f9b0002"
	GATTTx      = "6e753534-7061-7900-8000-00805f9b0003"
)
