#!/usr/bin/env python3
"""Generate language bindings for the NU-54V-DK payment protocol.

Source of truth: docs/content/specifications/protocol/payment-protocol.schema.json
(DF-20260925-02, [N04][N21][N25]). This script only derives code from it:

  go/protocol/types_gen.go      Go structs, EIP-712 type tables, reason/outcome constants
  ts/src/generated.ts           TypeScript interfaces and constants
  python/nu54_protocol/_generated.py  Python dataclasses and constants
  c/include/nu54_protocol.h     C encodeType strings, field counts, reason enum

Usage:
    python3 schema-gen/generate.py          # write files
    python3 schema-gen/generate.py --check  # fail if committed files differ
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
ROOT = PKG.parents[1]
SCHEMA = ROOT / "docs/content/specifications/protocol/payment-protocol.schema.json"
HEADER = "Code generated by packages/protocol/schema-gen/generate.py from payment-protocol.schema.json. DO NOT EDIT."

GO_TYPES = {"address": "common.Address", "uint256": "*big.Int", "uint64": "uint64",
            "bytes32": "[32]byte", "string": "string"}
TS_TYPES = {"address": "`0x${string}`", "uint256": "bigint", "uint64": "bigint",
            "bytes32": "`0x${string}`", "string": "string"}
PY_TYPES = {"address": "str", "uint256": "int", "uint64": "int", "bytes32": "str", "string": "str"}


def encode_type(name: str, fields: list[dict]) -> str:
    return f"{name}(" + ",".join(f"{f['type']} {f['name']}" for f in fields) + ")"


def pascal(name: str) -> str:
    return name[0].upper() + name[1:]


def const_name(value: str) -> str:
    return "".join(p.capitalize() for p in value.lower().split("_"))


def load() -> dict:
    schema = json.loads(SCHEMA.read_text())
    types = {**schema["eip712Types"], **schema["operatorSignedTypes"]}
    return {
        "domain": schema["eip712Domain"],
        "device": list(schema["eip712Types"]),
        "types": types,
        "reasons": schema["$defs"]["reason"]["enum"],
        "outcomes": schema["outcomes"],
        "messages": list(schema["messages"]),
        "version": schema["protocolVersion"],
        "messageFields": {name: _fields(schema, node) for name, node in schema["messages"].items()},
        "gatt": schema["gatt"],
    }


BYTE_KINDS = {"hex20", "hex32", "signature", "sessionId", "uint"}


def _kind(schema: dict, node: dict):
    """Compact CBOR field kind for codecs: a byte/uint kind, text, int, bool or a nested object."""
    ref = node.get("$ref")
    if ref:
        name = ref.rsplit("/", 1)[-1]
        if name in BYTE_KINDS:
            return name
        return _kind(schema, schema["$defs"][name])
    if node.get("type") == "object":
        return _fields(schema, node)
    if node.get("type") == "boolean":
        return "bool"
    if node.get("type") == "integer" or isinstance(node.get("const"), int):
        return "int"
    return "text"


def _fields(schema: dict, node: dict) -> dict:
    return {"fields": {k: _kind(schema, v) for k, v in node["properties"].items()}, "required": node.get("required", [])}


def gen_go(m: dict) -> str:
    out = [f"// {HEADER}", "", "package protocol", "", "import (", '\t"math/big"', "",
           '\t"github.com/ethereum/go-ethereum/common"', ")", "",
           f"// ProtocolVersion is the BLE payload version (field v).", f"const ProtocolVersion = {m['version']}", ""]
    for name, fields in m["types"].items():
        signer = "device" if name in m["device"] else "operator or merchant"
        out.append(f"// {name} is an EIP-712 struct signed by the {signer}.")
        out.append(f"type {name} struct {{")
        for f in fields:
            out.append(f"\t{pascal(f['name'])} {GO_TYPES[f['type']]} `json:\"{f['name']}\"`")
        out += ["}", ""]
    out.append("// EncodeType holds the EIP-712 encodeType string of every struct.")
    out.append("var EncodeType = map[string]string{")
    for name, fields in m["types"].items():
        out.append(f'\t"{name}": "{encode_type(name, fields)}",')
    out += ["}", "", "// DeviceSignedTypes are the only structs the device signs ([N04]).",
            "var DeviceSignedTypes = []string{" + ", ".join(f'"{n}"' for n in m["device"]) + "}", "",
            "// Reason is a refusal or session code.", "type Reason string", "", "const ("]
    for r in m["reasons"]:
        out.append(f'\tReason{const_name(r)} Reason = "{r}"')
    out += [")", "", "// Outcome is a kiosk-visible payment outcome.", "type Outcome string", "", "const ("]
    for o in m["outcomes"]:
        out.append(f'\tOutcome{pascal(o)} Outcome = "{o}"')
    out += [")", "", "// MessageTypes lists every BLE message type in the schema.", "var MessageTypes = []string{"]
    out += [f'\t"{t}",' for t in m["messages"]] + ["}", ""]
    return "\n".join(out)


def _domain_const(m: dict, field: str) -> str:
    return next(f["const"] for f in m["domain"] if f["name"] == field)


def gen_ts(m: dict) -> str:
    out = [f"// {HEADER}", "", f"export const PROTOCOL_VERSION = {m['version']} as const;", "",
           "/** EIP-712 domain constants; chainId and verifyingContract come from the deployment. */",
           "export const EIP712_DOMAIN = { name: " + json.dumps(_domain_const(m, "name")) + ", version: " + json.dumps(_domain_const(m, "version")) + " } as const;", ""]
    for name, fields in m["types"].items():
        out.append(f"export interface {name} {{")
        out += [f"  {f['name']}: {TS_TYPES[f['type']]};" for f in fields] + ["}", ""]
    out.append("export const EIP712_TYPES = {")
    for name, fields in m["types"].items():
        entries = ", ".join(f"{{ name: \"{f['name']}\", type: \"{f['type']}\" }}" for f in fields)
        out.append(f"  {name}: [{entries}],")
    out += ["} as const;", "", "export const ENCODE_TYPE: Record<keyof typeof EIP712_TYPES, string> = {"]
    out += [f'  {name}: "{encode_type(name, fields)}",' for name, fields in m["types"].items()]
    out += ["};", "", "export const DEVICE_SIGNED_TYPES = [" + ", ".join(f'"{n}"' for n in m["device"]) + "] as const;", "",
            "export const REASONS = [" + ", ".join(f'"{r}"' for r in m["reasons"]) + "] as const;",
            "export type Reason = (typeof REASONS)[number];", "",
            "export const OUTCOMES = [" + ", ".join(f'"{o}"' for o in m["outcomes"]) + "] as const;",
            "export type Outcome = (typeof OUTCOMES)[number];", "",
            "export const MESSAGE_TYPES = [" + ", ".join(f'"{t}"' for t in m["messages"]) + "] as const;",
            "export type MessageType = (typeof MESSAGE_TYPES)[number];", "",
            "/** CBOR field kinds per message (payment-protocol.md 4.2); nested objects carry their own fields. */",
            "export type FieldKind = \"hex20\" | \"hex32\" | \"signature\" | \"sessionId\" | \"uint\" | \"int\" | \"text\" | \"bool\" | ObjectKind;",
            "export interface ObjectKind { fields: Record<string, FieldKind>; required: readonly string[] }",
            "export const MESSAGE_FIELDS: Record<MessageType, ObjectKind> = " + json.dumps(m["messageFields"], indent=2) + ";", ""]
    return "\n".join(out)


def gen_py(m: dict) -> str:
    out = [f'"""{HEADER}"""', "", "from __future__ import annotations", "", "from dataclasses import dataclass", "",
           f"PROTOCOL_VERSION = {m['version']}", ""]
    for name, fields in m["types"].items():
        out += ["", "@dataclass(frozen=True)", f"class {name}:"]
        out += [f"    {f['name']}: {PY_TYPES[f['type']]}" for f in fields]
    out += ["", "", "EIP712_TYPES: dict[str, list[dict[str, str]]] = {"]
    for name, fields in m["types"].items():
        out.append(f"    {name!r}: " + json.dumps([{"name": f["name"], "type": f["type"]} for f in fields]) + ",")
    out += ["}", "", "ENCODE_TYPE: dict[str, str] = {"]
    out += [f"    {name!r}: {encode_type(name, fields)!r}," for name, fields in m["types"].items()]
    out += ["}", "", f"DEVICE_SIGNED_TYPES = {tuple(m['device'])!r}", f"REASONS = {tuple(m['reasons'])!r}",
            f"OUTCOMES = {tuple(m['outcomes'])!r}", f"MESSAGE_TYPES = {tuple(m['messages'])!r}", ""]
    return "\n".join(out)


def gen_c(m: dict) -> str:
    out = [f"/* {HEADER} */", "#ifndef NU54_PROTOCOL_H", "#define NU54_PROTOCOL_H", "",
           f"#define NU54_PROTOCOL_VERSION {m['version']}", "",
           "/* EIP-712 domain constants; chainId and verifyingContract come from the deployment. */",
           "#define NU54_EIP712_DOMAIN_NAME " + json.dumps(_domain_const(m, "name")),
           "#define NU54_EIP712_DOMAIN_VERSION " + json.dumps(_domain_const(m, "version")), ""]
    for name, fields in m["types"].items():
        macro = "".join("_" + c if c.isupper() else c.upper() for c in name).lstrip("_")
        out.append(f'#define NU54_ENCODE_TYPE_{macro} "{encode_type(name, fields)}"')
        out.append(f"#define NU54_FIELDS_{macro} {len(fields)}")
    out += ["", "typedef enum {"]
    out += [f"    NU54_REASON_{r} = {i}," for i, r in enumerate(m["reasons"])]
    out += ["    NU54_REASON_COUNT", "} nu54_reason_t;", "", "static const char *const nu54_reason_str[] = {"]
    out += [f'    "{r}",' for r in m["reasons"]] + ["};", ""]
    out += _c_gatt(m["gatt"])
    out += _c_message_tables(m["messageFields"])
    out += ["#endif /* NU54_PROTOCOL_H */", ""]
    return "\n".join(out)


C_KINDS = {"hex20": "NU54_K_HEX20", "hex32": "NU54_K_HEX32", "signature": "NU54_K_SIGNATURE", "sessionId": "NU54_K_SESSION_ID",
           "uint": "NU54_K_UINT", "int": "NU54_K_INT", "text": "NU54_K_TEXT", "bool": "NU54_K_BOOL"}


def _c_gatt(g: dict) -> list[str]:
    """GATT UUIDs as Zephyr BT_UUID_128_ENCODE arguments (payment-protocol.md 3)."""
    def enc(u: str) -> str:
        p = u.split("-")
        return f"0x{p[0]}, 0x{p[1]}, 0x{p[2]}, 0x{p[3]}, 0x{p[4]}"
    return ["/* GATT service of the payment protocol: pass to BT_UUID_128_ENCODE(). */",
            f"#define NU54_GATT_SERVICE_UUID_PARTS {enc(g['service'])}",
            f"#define NU54_GATT_RX_UUID_PARTS {enc(g['characteristics']['rx']['uuid'])}",
            f"#define NU54_GATT_TX_UUID_PARTS {enc(g['characteristics']['tx']['uuid'])}", ""]


def _c_message_tables(messages: dict) -> list[str]:
    """CBOR field tables per message (payment-protocol.md 4.2), the C form of MESSAGE_FIELDS."""
    out = ["/* CBOR field kinds per message; nested objects point to their own table. */",
           "typedef enum { NU54_K_HEX20, NU54_K_HEX32, NU54_K_SIGNATURE, NU54_K_SESSION_ID, NU54_K_UINT, NU54_K_INT,",
           "               NU54_K_TEXT, NU54_K_BOOL, NU54_K_OBJECT } nu54_field_kind_t;",
           "struct nu54_object;",
           "typedef struct { const char *name; nu54_field_kind_t kind; unsigned char required; const struct nu54_object *object; } nu54_field_t;",
           "typedef struct nu54_object { const nu54_field_t *fields; unsigned char count; } nu54_object_t;",
           "typedef struct { const char *type; const nu54_object_t *object; } nu54_message_t;", ""]
    tables: list[str] = []
    entries: list[str] = []

    def emit(cname: str, obj: dict) -> None:
        rows = []
        for fname, kind in obj["fields"].items():
            req = 1 if fname in obj["required"] else 0
            if isinstance(kind, dict):
                emit(f"{cname}_{fname}", kind)
                rows.append(f'{{"{fname}", NU54_K_OBJECT, {req}, &{cname}_{fname}}}')
            else:
                rows.append(f'{{"{fname}", {C_KINDS[kind]}, {req}, 0}}')
        tables.append(f"static const nu54_field_t {cname}_fields[] = {{{', '.join(rows)}}};")
        tables.append(f"static const nu54_object_t {cname} = {{{cname}_fields, {len(rows)}}};")

    for name, obj in messages.items():
        cname = "nu54_msg_" + name.replace(".", "_")
        emit(cname, obj)
        entries.append(f'{{"{name}", &{cname}}}')
    out += tables
    out += ["static const nu54_message_t nu54_messages[] = {", "    " + ",\n    ".join(entries), "};",
            f"#define NU54_MESSAGE_COUNT {len(entries)}", ""]
    return out


def gofmt(text: str) -> str:
    """Format Go output so generated files pass gofmt; left as-is when gofmt is missing."""
    exe = shutil.which("gofmt")
    if not exe:
        return text
    return subprocess.run([exe], input=text, capture_output=True, text=True, check=True).stdout


TARGETS = {
    "go/protocol/types_gen.go": lambda m: gofmt(gen_go(m)),
    "ts/src/generated.ts": gen_ts,
    "python/nu54_protocol/_generated.py": gen_py,
    "c/include/nu54_protocol.h": gen_c,
}


def main() -> int:
    model = load()
    stale = []
    for rel, fn in TARGETS.items():
        path, text = PKG / rel, fn(model)
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(rel)
    if stale:
        print("FAIL generated files are stale: " + ", ".join(stale))
        return 1
    if "--check" in sys.argv:
        print("OK generated files match the schema")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
