"""Render the resolved review without rewriting the pre-fix evidence."""
import json,hashlib
from pathlib import Path
O=Path(__file__).resolve().parent;R=O.parents[2]
read=lambda p:json.loads(p.read_text())
f=read(O/'findings.json');a=read(O/'structural-audit.json');g=read(O/'graph.json')
changes={'LG-01':'unknown의 원 allowance/실행 관측별 복구 전이 6개와 실패 근거 reorg 재검증 전이를 추가했다. 실행 노출이 있는 상태에서 review_ready로 돌아가 재서명할 수 없도록 제한했다.', 'LG-02':'CredentialStatus, PresentationSession, 불변 VerificationRecord를 분리했다. 같은 active credential을 서로 다른 challenge에 독립 제시하며, challenge 단회 소비와 철회 검사는 유지한다.', 'LG-03':'PR-COMMON / PR-GRANT / PR-GENERATE / PR-PUBLISH를 정의하고 PX05/06/07/11에서 참조한다. 최초 실행·재시도·공개가 동일 refund/authority/privacy/source/revision 조건을 검사한다.', 'LG-04':'OC17~20으로 refresh 요청/결과조회와 identity unlink 요청/결과조회를 추가했다. 회전 단일 successor, 이전 bearer 재전달 제한, 병렬 마지막 로그인 수단 제거 방지를 명시했다.', 'LG-05':'8개 DS와 전체 설계·인계서에 declaredScopeRequirementRefs와 transitiveTaskImpactRequirementRefs를 분리했다. WBS 104개 작업의 원 요구사항은 보존했다.'}
changes.update({'LG-06':'지급 확정 확인을 grant/generate/publish 공통 guard로 이동했다. reorg 시 지급 상태와 제한을 같은 CAS로 갱신하고, 복구는 payment_uncertain 이유만 해제한다.', 'LG-07':'refresh 결과의 generation과 현재 family generation을 비교한다. 이전 결과는 superseded로 토큰 없이 응답하며, 늦은 응답을 클라이언트에 설치하지 않는다.', 'LG-08':'목적별 동의 철회와 삭제 plan을 분리했다. purpose_blocked 상태는 원음을 임의 삭제하지 않으며, 승인된 plan 범위 밖 파일은 삭제하지 않는다.'})
changes.update({'LG-09':'지급 attempt의 거절·만료·확정 실패와 원 실행 복구 경로를 추가했다. 응답 유실과 부분 지급은 노출 해소 증거 없이 실패로 종료하지 않는다.', 'LG-10':'OC21/22 유료자원 환불 생성·조회 계약과 RF 환불 전이표를 추가했다. 현재 판매자 권한·원 funding·원장 revision을 결합하고 unknown 노출을 계속 차감한다.', 'LG-11':'삭제 완료는 대상 집합과 삭제 revision의 CAS, 발견 queue와 알려진 원천 작업의 종료 증거를 요구한다. 늦은 대상 추가는 완료 표시를 pending으로 돌리고 과거 receipt를 보존한다.'})
changes.update({'LG-12':'MPC 보류에서 재개할 7개 단계를 원 operation checkpoint·commit 증거·epoch에 연결했다. 불명 commit과 현재 권한 미충족은 보류하며 active 직접 복귀와 material 재사용을 금지한다.', 'LG-13':'늦은 DKG 완료 관측과 최초 지갑 활성화·주소 공개를 분리했다. MP03에 현재 enrollment 권한·보안 제한·operation revision CAS를 추가하고 조회 증명의 변경 권한을 명시적으로 차단했다.'})
changes.update({'LG-14':'청크의 불변 owner/대여/binding/device epoch/stream generation을 수신 commit에 결합했다. 계정 전환·반납 차단 이후에는 새 계정으로 저장·ACK하지 않으며 기존 파일 소유권·현재 읽기권·삭제 scope를 분리했다.', 'LG-15':'capture complete는 인증된 종료 범위와 정확한 durable 수신 구간·파일 검증·manifest CAS를 모두 요구한다. 재생 가능한 후미 유실은 partial이며 upload complete가 이를 승격하지 않는다.'})
changes.update({'LG-16':'키오스크 종료 요청·고객 세대·현재 boot·challenge에 정리 ACK를 결합했다. OC23/24로 확인·조회를 분리하고 현재 head CAS에서 clearance를 한 번 소비해 다음 세션을 발급한다. 늦은 지급 결과는 원 서버 거래에만 반영하며 현재 화면은 별도 수용 조건을 검사한다.'})
lines=['# 문서 관계 그래프와 논리 보완 결과','','**LG-01~16 모두 원본 설계에 수정 반영했다.** 기존 반례와 수정 전 파일은 보존했다. 논리 설계 회귀 검사와 문서 참조 검증을 수행했으며 제품의 보안·실기·체인 실행 검증은 아니다.','','x-theory 정의는 아직 미확인이다. 아래 분류와 관계는 중립적인 provenance 분석이며 x-theory 적용 완료를 주장하지 않는다.','',f'목록: {g["counts"]["document"]}개 문서/스키마/참조 SQL·GraphQL. 상세 의미 검토는 12개 구조화 핵심 문서 중심이다. 그래프는 {len(g["nodes"])}개 노드·{len(g["edges"])}개 관계이며, 과거 보존 디렉터리와 이 분석 폴더의 수정 전 스냅샷은 입력에서 제외한다.','','## 반영한 수정','']
for x in f['findings']:
 lines += [f'### {x["id"]} · 수정 반영','',changes[x['id']],'','수정 전 문제: '+x['claim'],'','회귀 기준: '+x['acceptance'],'']
 for e in x['resolutionEvidence']:
  assert hashlib.sha256((R/e['file']).read_bytes()).hexdigest()==e['sha256']
  lines += [f'- 현재 근거: [{Path(e["file"]).name}]({R/e["file"]}) — `{e["pointer"]}`']
 lines+=['']
lines+=['## 수정된 관계','', '```mermaid','flowchart LR',' R["요구 15"] --> T["작업 104 · 단계 320"]',' T --> P["DS01–08"]',' P --> S["주요 선언 범위"]',' T --> I["작업에서 계산한 영향 범위"]',' P --> C["API110 · 후보 계약24"]',' C --> G["공통 guard · 상태별 복구"]',' G --> V["설계 회귀 검사"]',' V -. "실제 실행 증거는 별도" .-> E["기기·앱·체인 검증 미실행"]','```','', '```mermaid','stateDiagram-v2',' execution_pending --> unknown: 응답 유실',' unknown --> execution_pending: 원 실행 pending 확인',' unknown --> result_observed: 원 receipt와 실제 효과 확인',' result_observed --> completed: 확정 정책과 현재성 검사',' unknown --> failed_confirmed: 확정 실패 및 노출 해소',' failed_confirmed --> unknown: 실패 근거 reorg','```','', '```mermaid','flowchart LR',' C["Credential active"] --> A["Presentation A / challenge A"]',' C --> B["Presentation B / challenge B"]',' A --> VA["불변 Verification A"]',' B --> VB["불변 Verification B"]',' RE["현재 철회·신뢰·만료 검사"] --> A',' RE --> B','```','', '## 검증 결과와 경계','',f'- WBS 의존 관계 {a["wbsDependencyEdges"]}개: 순환 {len(a["wbsCycles"])}개.',f'- 원본 source hash {a["sourceHashChecks"]}개: 현재 참조 불일치 {len(a["hashMismatches"])}개.', '- `validate_logic_fixes.py`: 수정 전 결함 재현과 수정 후 전이·객체·guard·계약 연결·범위 구분을 검사한다. 형식 모델/판정표 검사이며 실제 경쟁 상황이나 암호 구현을 증명하지 않는다.', '- 후보 API는 논리 계약으로 추가했다. 기존 카탈로그110개를 런타임 API가 구현된 것으로 변경하지 않았다.', '- 정책19개와 RR-DEC-01은 미선택 상태를 유지한다.','', '## 산출물과 재현','', '- [전체 그래프 JSON](graph.json) · [DOT](graph.dot) · [검토 주석 포함 그래프](review-graph.json)', '- [수정 전 근거와 수정 상태](findings.json) · [1차 해시 변경](source-pin-rebase.json) · [후속 해시 변경](round2-source-pin-rebase.json) · [3차 해시 변경](round3-source-pin-rebase.json) · [4차 해시 변경](round4-source-pin-rebase.json) · [5차 해시 변경](round5-source-pin-rebase.json) · [6차 해시 변경](round6-source-pin-rebase.json) · [검사 결과](correction-validation.json)','', '```sh','python3 content/analysis/document-logic/build_graph.py','python3 content/analysis/document-logic/validate_logic_fixes.py','python3 content/analysis/document-logic/validate_followup.py','python3 content/analysis/document-logic/validate_round3.py','python3 content/analysis/document-logic/validate_round4.py','python3 content/analysis/document-logic/validate_round5.py','python3 content/analysis/document-logic/validate_round6.py','python3 content/analysis/document-logic/render_review.py','```']
v=read(O/'correction-validation.json')
lines += ['', '## 지급·환불·삭제 완료 경로', '', '```mermaid', 'flowchart LR', ' P["원 지급 attempt"] --> PF["미노출 거절·만료 / 노출 해소된 확정 실패"]', ' P --> PU["응답 유실·상충: unknown"]', ' PU --> PR["원 실행 재조회"]', ' R["OC21 환불 생성"] --> A["현재 판매자 권한·원 funding·잔여 한도"]', ' A --> L["원 attempt 예약 원장"]', ' L --> U["unknown: 예약 유지"]', ' U --> Q["OC22 원 환불 결과 조회"]', ' Q --> L', ' D["삭제 대상 추가"] --> REV["대상·삭제 revision 증가 + pending"]', ' REV --> CAS["현재 revision + 대상 증거 + 원천 종료 확인"]', ' CAS --> DONE["현재 완료 표시 + 불변 receipt"]', ' DONE --> D', '```', '', f"검사 결과: 기존 정합성 검사 {v['existingValidatorsPassed']}개, 최초 회귀 {v['regression']['checksPassed']}개, 후속 예제 {v['followup']['casesPassed']}개, 3차 예제 {v['round3']['casesPassed']}개·4차 예제 {v['round4']['casesPassed']}개·5차 예제 {v['round5']['casesPassed']}개·6차 예제 {v['round6']['casesPassed']}개 통과. 환불 원장 산술과 CAS 순서 검사는 유한 설계 예제이며 실제 저장소 동시성·체인 확정 검증을 대체하지 않는다."]
lines += ['', '## MPC 보류·현재 권한 경계', '', '```mermaid', 'flowchart LR', ' H["MPC 보류"] --> C["원 checkpoint · commit 증거 확인"]', ' C --> U["commit 불명: 보류 유지"]', ' C --> B["미commit: 원 epoch의 증명된 단계"]', ' C --> A["commit 이후: 동일 새 epoch의 단계"]', ' B --> G["현재 변경 권한·제한·revision 검사"]', ' A --> G', ' G --> R["MR01–07 원 작업 재개"]', ' D["늦은 DKG 완료"] --> E["원 operation에 관측 기록"]', ' E --> P["MPC-ACTIVATE 검사"]', ' P --> OK["조건 충족: 활성화"]', ' P --> NO["권한 철회·상태 불일치: 보류"]', ' Q["결과 조회 증명"] --> READ["현 범위의 제한된 조회만"]', '```', '', '원 복구 원칙을 단계별로 구체화한 설계다. 선택된 MPC 제공자의 실제 재개·중단 지원과 분산 저장·서명 검증은 아직 수행하지 않았다.']
lines += ['', '## 녹음의 계정·대여 경계와 완료 조건', '', '```mermaid', 'flowchart LR', ' S["녹음 시작: 원 owner·대여·기기 세대 고정"] --> C["청크 인증 + 현재 수신 gate"]', ' X["계정 전환·반납 경계"] --> G["generation 무효화 · 수신 차단"]', ' G --> C', ' C --> D["허용된 원 namespace에 저장 후 ACK"]', ' C --> NO["불일치·차단: 저장·ACK 금지"]', ' D --> F["종료 표식·정확한 구간·파일 검증"]', ' F --> OK["capture complete"]', ' F --> PART["후미 유실·종료 불명: partial"]', ' PART --> U["파일 upload complete여도 partial 유지"]', ' D --> R["기존 파일: 원 owner의 현재 읽기권 검사"]', '```', '', '수신 gate의 실제 native 원자성, BLE 인증된 wire/종료 표식, RAM·DMA 정리와 lease 만료는 구현·실기 검증 대상이다. 원격 철회의 오프라인 즉시 적용이나 이미 공개된 데이터 회수는 보장하지 않는다.']
lines += ['', '## 키오스크 다음 고객 전환', '', '```mermaid', 'flowchart LR', ' E["종료 요청: local view 차단"] --> D["서버 deny + 정리 challenge"]', ' D --> C["OC23: 원 종료·고객·boot·revision의 정리 ACK"]', ' C --> R["clearance receipt"]', ' R --> N["현 head CAS + 한 번 소비"]', ' N --> S["새 고객 세션"]', ' Q["OC24: 원 종료 현재 상태 조회"] --> R', ' OLD["늦은 결제 결과"] --> SERVER["원 order/attempt 대사"]', ' OLD --> V["현재 context·view·권한 수용 검사"]', ' V --> NO["다른 손님이면 화면 반영 금지"]', '```', '', '정리 ACK는 선정 profile의 앱 보고다. 실제 native 정리, 프로세스 재시작, 중복 요청 경합의 실기 검증은 별도로 필요하다. 고객 개인 결과 조회 증명의 발급·전달 profile(KP05)은 미선정이며 기존 원 eligibility/claim 권한을 대체하지 않는다.']
(O/'review.md').write_text('\n'.join(lines)+'\n')
for x in f['findings']:
 id='finding:'+x['id'];g['nodes'].append(dict(id=id,kind='finding',label=x['id']+' 수정 반영',status=x['status'],source='content/analysis/document-logic/findings.json'))
 for e in x['resolutionEvidence']:g['edges'].append(dict(source=id,target='doc:'+e['file'],relation='resolved_by_design_change',provenance=e,basis='validated_design_correction'))
g['counts']['finding']=len(f['findings']);(O/'review-graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n')
print('Updated resolved findings, graph annotations and Mermaid views.')
